//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub mod prelude;

pub mod pokemon_v2_language;
pub mod pokemon_v2_pokemon;
pub mod pokemon_v2_pokemonspecies;
pub mod pokemon_v2_pokemonspeciesname;
pub mod pokemon_v2_pokemonsprites;
