//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pokemon_v2_pokemonspeciesname")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub genus: String,
    pub language_id: Option<i64>,
    pub pokemon_species_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pokemon_v2_language::Entity",
        from = "Column::LanguageId",
        to = "super::pokemon_v2_language::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PokemonV2Language,
    #[sea_orm(
        belongs_to = "super::pokemon_v2_pokemonspecies::Entity",
        from = "Column::PokemonSpeciesId",
        to = "super::pokemon_v2_pokemonspecies::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PokemonV2Pokemonspecies,
}

impl Related<super::pokemon_v2_language::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonV2Language.def()
    }
}

impl Related<super::pokemon_v2_pokemonspecies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonV2Pokemonspecies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
