//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pokemon_v2_pokemon")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub order: Option<i64>,
    pub height: Option<i64>,
    pub weight: Option<i64>,
    pub base_experience: Option<i64>,
    #[sea_orm(ignore, column_type = "custom(\"NUM\")", select_as = "text", nullable)]
    pub is_default: String,
    pub pokemon_species_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pokemon_v2_pokemonspecies::Entity",
        from = "Column::PokemonSpeciesId",
        to = "super::pokemon_v2_pokemonspecies::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PokemonV2Pokemonspecies,
    #[sea_orm(has_many = "super::pokemon_v2_pokemonsprites::Entity")]
    PokemonV2Pokemonsprites,
}

impl Related<super::pokemon_v2_pokemonspecies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonV2Pokemonspecies.def()
    }
}

impl Related<super::pokemon_v2_pokemonsprites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonV2Pokemonsprites.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
