//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pokemon_v2_pokemonspecies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pokemon_v2_pokemon::Entity")]
    PokemonV2Pokemon,
    #[sea_orm(has_many = "super::pokemon_v2_pokemonspeciesname::Entity")]
    PokemonV2Pokemonspeciesname,
}

impl Related<super::pokemon_v2_pokemon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonV2Pokemon.def()
    }
}

impl Related<super::pokemon_v2_pokemonspeciesname::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonV2Pokemonspeciesname.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
