//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "pokemon_v2_pokemonsprites")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub pokemon_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sprites: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pokemon_v2_pokemon::Entity",
        from = "Column::PokemonId",
        to = "super::pokemon_v2_pokemon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PokemonV2Pokemon,
}

impl Related<super::pokemon_v2_pokemon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PokemonV2Pokemon.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
