//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

#![allow(unused_imports)]

pub use super::{
    pokemon_v2_language::Entity as PokemonV2Language,
    pokemon_v2_pokemon::Entity as PokemonV2Pokemon,
    pokemon_v2_pokemonspecies::Entity as PokemonV2Pokemonspecies,
    pokemon_v2_pokemonspeciesname::Entity as PokemonV2Pokemonspeciesname,
    pokemon_v2_pokemonsprites::Entity as PokemonV2Pokemonsprites,
};
